# Generated by Django 6.0.3 on 2026-06-30 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='Kazakhstan', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cuisine', models.CharField(default='Казахская', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Dishes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlavorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(blank=True, max_length=50)),
                ('emoji', models.CharField(max_length=10)),
                ('color', models.CharField(help_text='HEX color, e.g. #f59e0b', max_length=7)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Flavor Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(help_text='Markdown content')),
                ('order', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=50)),
            ],
            options={
                'ordering': ['level__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('emoji', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('xp_required', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('style', models.CharField(choices=[('pilsener', 'Pilsener'), ('lager', 'Lager'), ('dark_lager', 'Dark Lager'), ('wheat', 'Wheat Beer'), ('stout', 'Stout'), ('ale', 'Ale'), ('ipa', 'IPA'), ('other', 'Other')], default='lager', max_length=20)),
                ('style_display', models.CharField(blank=True, help_text='Human-readable style name', max_length=50)),
                ('abv', models.FloatField(help_text='Alcohol by volume %')),
                ('ibu', models.IntegerField(default=0, help_text='International Bitterness Units')),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, help_text='Эмоциональный слоган', max_length=200)),
                ('serving_temp', models.CharField(default='4-6°C', max_length=20)),
                ('density', models.CharField(blank=True, help_text='e.g. 12°P', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('rating', models.FloatField(default=4.5)),
                ('rating_count', models.IntegerField(default=0)),
                ('notes_count', models.IntegerField(default=0)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='api.brand')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('avatar_emoji', models.CharField(default='🎓', max_length=10)),
                ('text', models.TextField()),
                ('rating', models.FloatField(default=5.0)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_reviews', to='api.beer')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='FlavorPyramid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(default='Эмоции и ассоциации', max_length=100)),
                ('top_description', models.TextField(help_text='Эмоции: лето, свобода, ностальгия...')),
                ('heart_title', models.CharField(default='Ароматические ноты', max_length=100)),
                ('heart_description', models.TextField(help_text='Цитрус, хлеб, мёд, хвоя...')),
                ('base_title', models.CharField(default='Базовые вкусы', max_length=100)),
                ('base_description', models.TextField(help_text='Горечь, сладость, кислота...')),
                ('beer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pyramid', to='api.beer')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('options', models.JSONField(help_text='["Option A", "Option B", "Option C", "Option D"]')),
                ('correct_index', models.IntegerField(help_text='0-based index of correct option')),
                ('explanation', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.schoollevel'),
        ),
        migrations.CreateModel(
            name='TastingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_text', models.TextField()),
                ('rating', models.FloatField(default=4.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasting_notes', to='api.beer')),
                ('selected_notes', models.ManyToManyField(blank=True, to='api.flavorcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasting_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('total_xp', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('tastings_count', models.IntegerField(default=0)),
                ('current_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.schoollevel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeerFlavorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField(help_text='Intensity 0-100')),
                ('layer', models.CharField(choices=[('top', 'Top (Emotions)'), ('heart', 'Heart (Aromas)'), ('base', 'Base (Tastes)')], default='heart', max_length=10)),
                ('sub_description', models.CharField(blank=True, help_text='e.g. Лимонная цедра', max_length=100)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor_notes', to='api.beer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_notes', to='api.flavorcategory')),
            ],
            options={
                'ordering': ['-intensity'],
                'unique_together': {('beer', 'category')},
            },
        ),
        migrations.CreateModel(
            name='FoodPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percent', models.IntegerField(help_text='Match 0-100')),
                ('why_it_works', models.TextField(help_text='Объяснение почему это сочетание работает')),
                ('flavor_bridges', models.JSONField(default=list, help_text='["🔥 Горечь × Дым", "🍋 Цитрус освежает"]')),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_pairings', to='api.beer')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_pairings', to='api.dish')),
            ],
            options={
                'ordering': ['-match_percent'],
                'unique_together': {('beer', 'dish')},
            },
        ),
    ]
