# Generated by Django 4.2.30 on 2026-09-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='foodpairing',
            options={'ordering': ['-compatibility_score'], 'verbose_name': 'Food Pairing', 'verbose_name_plural': 'Food Pairings'},
        ),
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ['venue', 'table_number'], 'verbose_name': 'QR-код', 'verbose_name_plural': 'QR-коды'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['name'], 'verbose_name': 'Член команды', 'verbose_name_plural': 'Команда'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name'], 'verbose_name': 'Заведение', 'verbose_name_plural': 'Заведения'},
        ),
        migrations.AddField(
            model_name='brand',
            name='is_horeca_only',
            field=models.BooleanField(default=False, help_text='Доступно только в заведениях HoReCa (обычно = True для разливного)', verbose_name='Только HoReCa'),
        ),
        migrations.AddField(
            model_name='brand',
            name='packaging_type',
            field=models.CharField(choices=[('BOTTLE', 'Бутылка'), ('CAN', 'Банка'), ('DRAFT', 'Разливное')], default='BOTTLE', max_length=10, verbose_name='Тип упаковки'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='abv',
            field=models.FloatField(blank=True, null=True, verbose_name='Алкоголь %'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_owner',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Владелец бренда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Изображение'),
        ),
    ]
