# Generated by Django 4.2.30 on 2026-09-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_brand_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="abv_estimated",
            field=models.BooleanField(
                default=False, verbose_name="ABV оценочный — уточнить"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="accent",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                verbose_name="Акцентный цвет (hex)",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="display_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Отображаемое имя"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="origin",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Происхождение"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=80, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="style_family",
            field=models.CharField(
                default="LAGER",
                help_text="PILSNER / LAGER / CZECH_LAGER / AMBER_LAGER / STRONG_LAGER / RICE_LAGER …",
                max_length=30,
                verbose_name="Семейство стиля (приор движка)",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="tagline",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Короткий слоган"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="vector_override",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="Ручной сенсорный вектор (override движка)",
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="display_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Отображаемое имя"
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="emoji",
            field=models.CharField(
                blank=True, default="", max_length=8, verbose_name="Эмодзи"
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=80, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="synonyms",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Синонимы для поиска"
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="tags",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Ароматические теги"
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="vector",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Сенсорный вектор блюда (0..1)"
            ),
        ),
        migrations.AddField(
            model_name="flavornote",
            name="axes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Как нота влияет на вектор пива: {"bitter": 0.9}',
                verbose_name="Сенсорные оси (axis → вес 0..1)",
            ),
        ),
        migrations.AddField(
            model_name="flavornote",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=80, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AddField(
            model_name="flavornote",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="Ароматические теги (мосты к еде)",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="brands",
            field=models.ManyToManyField(
                blank=True,
                related_name="venues",
                to="api.brand",
                verbose_name="Сорта в наличии",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="venue",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AddField(
            model_name="venue",
            name="menu_dishes",
            field=models.ManyToManyField(
                blank=True,
                related_name="venues",
                to="api.dish",
                verbose_name="Блюда меню",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=80, null=True, unique=True, verbose_name="Slug"
            ),
        ),
    ]
