# Generated by Django 4.2.30 on 2026-09-18 00:05

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_flavor_tree_v2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "venue_name",
                    models.CharField(max_length=200, verbose_name="Заведение"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Имя"
                    ),
                ),
                ("phone", models.CharField(max_length=40, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Город"
                    ),
                ),
                (
                    "tables",
                    models.IntegerField(blank=True, null=True, verbose_name="Столов"),
                ),
                (
                    "plan_interest",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Интересующий тариф",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Комментарий"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="landing",
                        max_length=80,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новая"),
                            ("CONTACTED", "Связались"),
                            ("DEMO", "Показали демо"),
                            ("TRIAL", "Запустили пробный"),
                            ("WON", "Оплатил"),
                            ("LOST", "Отказ"),
                        ],
                        default="NEW",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки (воронка)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="qrcode",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="label",
            field=models.CharField(
                blank=True,
                default="",
                max_length=80,
                verbose_name="Метка (Стол 5 / Терраса)",
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="last_scan_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последний скан"
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="accent",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                verbose_name="Акцентный цвет (hex)",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="cover_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Обложка меню"
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="currency",
            field=models.CharField(default="₸", max_length=8, verbose_name="Валюта"),
        ),
        migrations.AddField(
            model_name="venue",
            name="instagram",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Instagram"
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="menu_headline",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Например: «Что взять к вашему блюду?»",
                max_length=200,
                verbose_name="Заголовок меню",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=40, verbose_name="Телефон"
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Обновлено"
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="wifi_password",
            field=models.CharField(
                blank=True,
                default="",
                max_length=80,
                verbose_name="Пароль Wi-Fi (показать гостю)",
            ),
        ),
        migrations.CreateModel(
            name="VenueAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail для входа"
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Пароль (хеш)",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Контактное лицо",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="Телефон"
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("TRIAL", "Пробный (14 дней)"),
                            ("START", "Старт"),
                            ("PRO", "Про"),
                            ("NETWORK", "Сеть"),
                        ],
                        default="TRIAL",
                        max_length=10,
                        verbose_name="Тариф",
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Пробный период до"
                    ),
                ),
                (
                    "paid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Оплачено до"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "api_token",
                    models.CharField(
                        default=api.models._new_token,
                        max_length=64,
                        unique=True,
                        verbose_name="Токен API",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний вход"
                    ),
                ),
                (
                    "venue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to="api.venue",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аккаунт заведения",
                "verbose_name_plural": "Аккаунты заведений",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "table_number",
                    models.IntegerField(blank=True, null=True, verbose_name="Стол"),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Сессия гостя",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="User-Agent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Когда"
                    ),
                ),
                (
                    "qrcode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="api.qrcode",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_events",
                        to="api.venue",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Скан QR",
                "verbose_name_plural": "Сканы QR",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MenuEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DISH_VIEW", "Открыл блюдо"),
                            ("PAIR_VIEW", "Увидел подбор"),
                            ("BEER_VIEW", "Открыл сорт"),
                            ("ORDER_INTENT", "Нажал «Заказать»"),
                        ],
                        max_length=16,
                        verbose_name="Событие",
                    ),
                ),
                (
                    "dish_slug",
                    models.SlugField(
                        blank=True, default="", max_length=80, verbose_name="Блюдо"
                    ),
                ),
                (
                    "beer_slug",
                    models.SlugField(
                        blank=True, default="", max_length=80, verbose_name="Сорт"
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Оценка подбора"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Цена позиции, ₸",
                    ),
                ),
                (
                    "table_number",
                    models.IntegerField(blank=True, null=True, verbose_name="Стол"),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Сессия гостя",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Когда"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_events",
                        to="api.venue",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие меню",
                "verbose_name_plural": "События меню",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VenueMenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("BEER", "Пиво"), ("DISH", "Блюдо")],
                        max_length=8,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "ref_slug",
                    models.SlugField(
                        max_length=80,
                        verbose_name="Slug каталога (brand.slug / dish.slug)",
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Своё название",
                    ),
                ),
                (
                    "custom_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="Своё описание",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="Раздел меню",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Цена, ₸",
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="0.5 л, 300 г — печатается рядом с ценой",
                        max_length=40,
                        verbose_name="Объём / выход",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="В наличии (стоп-лист)"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Хит / рекомендуем"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="api.venue",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция меню заведения",
                "verbose_name_plural": "Позиции меню заведений",
                "ordering": ["kind", "sort_order", "ref_slug"],
                "unique_together": {("venue", "kind", "ref_slug")},
            },
        ),
    ]
