# Generated by Django 4.2.30 on 2026-09-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dish_options_dish_cooking_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpairing',
            name='compatibility_score',
            field=models.IntegerField(verbose_name='Совместимость (оценка 1-5 или %)'),
        ),
        migrations.AlterField(
            model_name='foodpairing',
            name='pairing_type',
            field=models.CharField(choices=[('COMPLEMENT', 'Дополняет (Complement)'), ('CONTRAST', 'Контрастирует (Contrast)'), ('CLEANSE', 'Очищает (Cleanse)'), ('BRIDGE', 'Мостик (Bridge)')], max_length=20, verbose_name='Тип пары'),
        ),
    ]
