# Generated by Django 4.2.30 on 2026-09-06 22:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('brand_owner', models.CharField(max_length=100, verbose_name='Владелец бренда')),
                ('style', models.CharField(max_length=100, verbose_name='Стиль')),
                ('abv', models.FloatField(verbose_name='Алкоголь %')),
                ('density', models.CharField(blank=True, default='', max_length=100, verbose_name='Плотность')),
                ('fermentation_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Тип брожения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.URLField(max_length=500, verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(choices=[(1, 'Новичок'), (2, 'Исследователь'), (3, 'Знаток'), (4, 'Сомелье')], unique=True, verbose_name='Уровень')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('color', models.CharField(default='#F7941D', max_length=20, verbose_name='Цвет (hex)')),
                ('required_score', models.IntegerField(default=0, verbose_name='Необходимый балл')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('cuisine', models.CharField(choices=[('KZ', 'Казахская'), ('RU', 'Русская'), ('EU', 'Европейская'), ('ASIAN', 'Азиатская'), ('OTHER', 'Другая')], max_length=20, verbose_name='Кухня')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.URLField(blank=True, default='', max_length=500, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='FlavorNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('technical_term', models.CharField(blank=True, default='', max_length=100, verbose_name='Техническое название')),
                ('wheel_code', models.CharField(blank=True, default='', max_length=10, verbose_name='Код колеса вкусов')),
                ('category', models.CharField(choices=[('TOP', 'Верхние ноты'), ('HEART', 'Ноты сердца'), ('BASE', 'Базовые ноты')], max_length=10, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(max_length=10, verbose_name='Иконка (emoji)')),
                ('reference_material', models.CharField(blank=True, default='', max_length=200, verbose_name='Эталонный материал')),
                ('is_off_flavour', models.BooleanField(default=False, verbose_name='Off-flavour (дефект)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Вкусовая нота',
                'verbose_name_plural': 'Вкусовые ноты',
                'ordering': ['sort_order', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('role', models.CharField(max_length=150, verbose_name='Роль')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('avatar', models.URLField(blank=True, default='', max_length=500, verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Команда',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('venue_type', models.CharField(choices=[('BAR', 'Бар'), ('RESTAURANT', 'Ресторан'), ('PUB', 'Паб'), ('CAFE', 'Кафе'), ('OTHER', 'Другое')], max_length=50, verbose_name='Тип заведения')),
                ('logo', models.URLField(blank=True, default='', max_length=500, verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
            },
        ),
        migrations.CreateModel(
            name='ServingRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serving_temp_min', models.FloatField(verbose_name='Т° мин, °C')),
                ('serving_temp_max', models.FloatField(verbose_name='Т° макс, °C')),
                ('glass_type', models.CharField(max_length=100, verbose_name='Тип бокала')),
                ('seasonality', models.CharField(blank=True, default='', max_length=100, verbose_name='Сезонность')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serving_recommendation', to='api.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Рекомендация по подаче',
                'verbose_name_plural': 'Рекомендации по подаче',
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_number', models.IntegerField(verbose_name='Номер столика')),
                ('unique_token', models.CharField(max_length=64, unique=True, verbose_name='Уникальный токен')),
                ('scans_count', models.IntegerField(default=0, verbose_name='Количество сканирований')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='api.venue', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'QR-код',
                'verbose_name_plural': 'QR-коды',
            },
        ),
        migrations.CreateModel(
            name='FoodPairing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compatibility_score', models.IntegerField(verbose_name='Совместимость (%)')),
                ('pairing_type', models.CharField(choices=[('COMPLEMENT', 'Дополняет'), ('CONTRAST', 'Контрастирует'), ('BRIDGE', 'Мостик')], max_length=20, verbose_name='Тип пары')),
                ('explanation', models.TextField(verbose_name='Обоснование')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_pairings', to='api.brand', verbose_name='Бренд')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_pairings', to='api.dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Food Pairing',
                'verbose_name_plural': 'Food Pairings',
            },
        ),
        migrations.CreateModel(
            name='AnonymousSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_levels', models.IntegerField(default=0, verbose_name='Пройдено уровней')),
                ('score', models.IntegerField(default=0, verbose_name='Баллы')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='Предпочтения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='api.qrcode', verbose_name='QR-код')),
            ],
            options={
                'verbose_name': 'Анонимная сессия',
                'verbose_name_plural': 'Анонимные сессии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlavorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer', models.CharField(choices=[('TOP', 'Верхние ноты'), ('HEART', 'Ноты сердца'), ('BASE', 'Базовые ноты')], max_length=10, verbose_name='Слой пирамиды')),
                ('intensity', models.IntegerField(verbose_name='Интенсивность (1-10)')),
                ('sommelier_note', models.TextField(blank=True, default='', verbose_name='Комментарий сомелье')),
                ('sommelier_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Имя сомелье')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor_profiles', to='api.brand', verbose_name='Бренд')),
                ('flavor_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor_profiles', to='api.flavornote', verbose_name='Вкусовая нота')),
            ],
            options={
                'verbose_name': 'Вкусовой профиль',
                'verbose_name_plural': 'Вкусовые профили',
                'ordering': ['-intensity'],
                'unique_together': {('brand', 'flavor_note')},
            },
        ),
    ]
