# Generated by Django 4.2.30 on 2026-09-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dish_options_alter_foodpairing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['cuisine', 'name'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AddField(
            model_name='dish',
            name='cooking_method',
            field=models.CharField(choices=[('FRIED', 'Жарка'), ('GRILLED', 'Гриль'), ('BAKED', 'Запекание'), ('BOILED', 'Варка'), ('STEAMED', 'На пару'), ('RAW', 'Сырое'), ('CURED', 'Вяленое'), ('FERMENTED', 'Ферментация'), ('OTHER', 'Без термообработки / Другое')], default='GRILLED', max_length=20, verbose_name='Способ приготовления'),
        ),
        migrations.AddField(
            model_name='dish',
            name='dominant_taste',
            field=models.CharField(choices=[('SALTY', 'Солёное'), ('SWEET', 'Сладкое'), ('SOUR', 'Кислое'), ('BITTER', 'Горькое'), ('UMAMI', 'Умами'), ('SPICY', 'Острое'), ('MIXED', 'Микс')], default='UMAMI', max_length=10, verbose_name='Доминирующий вкус'),
        ),
        migrations.AddField(
            model_name='dish',
            name='fat_level',
            field=models.CharField(choices=[('LOW', 'Низкая'), ('MEDIUM', 'Средняя'), ('HIGH', 'Высокая')], default='MEDIUM', max_length=10, verbose_name='Жирность'),
        ),
        migrations.AddField(
            model_name='dish',
            name='weight',
            field=models.CharField(choices=[('LIGHT', 'Лёгкое'), ('MEDIUM', 'Среднее'), ('HEAVY', 'Тяжёлое')], default='MEDIUM', max_length=10, verbose_name='Вес блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(blank=True, default='Основное', max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='cuisine',
            field=models.CharField(choices=[('KZ', 'Казахская'), ('ITALIAN', 'Итальянская'), ('JAPANESE', 'Японская'), ('AMERICAN', 'Американская'), ('MEXICAN', 'Мексиканская'), ('GERMAN', 'Немецкая'), ('OTHER', 'Другая')], max_length=20, verbose_name='Кухня'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
