# Generated by Django 4.2.30 on 2026-09-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_foodpairing_compatibility_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='brands/', verbose_name='Изображение / Бутылка'),
        ),
    ]
